In [ ]:
# This dataset has funding information of the Indian startups from January 2015 to August 2017.

# Feature Details:
# SNo - Serial number.
# Date - Date of funding in format DD/MM/YYYY.
# StartupName - Name of the startup which got funded.
# IndustryVertical - Industry to which the startup belongs.
# SubVertical - Sub-category of the industry type.
# CityLocation - City which the startup is based out of.
# InvestorsName - Name of the investors involved in the funding round.
# InvestmentType - Either Private Equity or Seed Funding.
# AmountInUSD - Funding Amount in USD.
# Remarks - Other information, if any.


# Find out what type of startups are getting funded in the last few years?
# Who are the important investors?
# What are the hot fields that get a lot of funding these days?

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("startup_funding.csv")

In [5]:
df.head()

,SNo,Date,StartupName,IndustryVertical,SubVertical,CityLocation,InvestorsName,InvestmentType,AmountInUSD,Remarks
0,0,01/08/2017,TouchKin,Technology,Predictive Care Platform,Bangalore,Kae Capital,Private Equity,"1,300,000",NaN
1,1,02/08/2017,Ethinos,Technology,Digital Marketing Agency,Mumbai,Triton Investment Advisors,Private Equity,NaN,NaN
2,2,02/08/2017,Leverage Edu,Consumer Internet,Online platform for Higher Education Services,New Delhi,"Kashyap Deorah, Anand Sankeshwar, Deepak Jain,...",Seed Funding,NaN,NaN
3,3,02/08/2017,Zepo,Consumer Internet,DIY Ecommerce platform,Mumbai,"Kunal Shah, LetsVenture, Anupam Mittal, Hetal ...",Seed Funding,"500,000",NaN
4,4,02/08/2017,Click2Clinic,Consumer Internet,healthcare service aggregator,Hyderabad,"Narottam Thudi, Shireesh Palle",Seed Funding,"850,000",NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2372 entries, 0 to 2371
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SNo               2372 non-null   int64
 1   Date              2372 non-null   object
 2   StartupName       2372 non-null   object
 3   IndustryVertical  2201 non-null   object
 4   SubVertical       1436 non-null   object
 5   CityLocation      2193 non-null   object
 6   InvestorsName     2364 non-null   object
 7   InvestmentType    2371 non-null   object
 8   AmountInUSD       1525 non-null   object
 9   Remarks           419 non-null    object
dtypes: int64(1), object(9)
memory usage: 185.4+ KB

In [10]:
df[df.dtypes[df.dtypes=='object'].index][:5]

,Date,StartupName,IndustryVertical,SubVertical,CityLocation,InvestorsName,InvestmentType,AmountInUSD,Remarks
0,01/08/2017,TouchKin,Technology,Predictive Care Platform,Bangalore,Kae Capital,Private Equity,"1,300,000",NaN
1,02/08/2017,Ethinos,Technology,Digital Marketing Agency,Mumbai,Triton Investment Advisors,Private Equity,NaN,NaN
2,02/08/2017,Leverage Edu,Consumer Internet,Online platform for Higher Education Services,New Delhi,"Kashyap Deorah, Anand Sankeshwar, Deepak Jain,...",Seed Funding,NaN,NaN
3,02/08/2017,Zepo,Consumer Internet,DIY Ecommerce platform,Mumbai,"Kunal Shah, LetsVenture, Anupam Mittal, Hetal ...",Seed Funding,"500,000",NaN
4,02/08/2017,Click2Clinic,Consumer Internet,healthcare service aggregator,Hyderabad,"Narottam Thudi, Shireesh Palle",Seed Funding,"850,000",NaN

In [12]:
df.select_dtypes(include='object')[:5]  ## There are two ways to get data a/c to dtypes

,Date,StartupName,IndustryVertical,SubVertical,CityLocation,InvestorsName,InvestmentType,AmountInUSD,Remarks
0,01/08/2017,TouchKin,Technology,Predictive Care Platform,Bangalore,Kae Capital,Private Equity,"1,300,000",NaN
1,02/08/2017,Ethinos,Technology,Digital Marketing Agency,Mumbai,Triton Investment Advisors,Private Equity,NaN,NaN
2,02/08/2017,Leverage Edu,Consumer Internet,Online platform for Higher Education Services,New Delhi,"Kashyap Deorah, Anand Sankeshwar, Deepak Jain,...",Seed Funding,NaN,NaN
3,02/08/2017,Zepo,Consumer Internet,DIY Ecommerce platform,Mumbai,"Kunal Shah, LetsVenture, Anupam Mittal, Hetal ...",Seed Funding,"500,000",NaN
4,02/08/2017,Click2Clinic,Consumer Internet,healthcare service aggregator,Hyderabad,"Narottam Thudi, Shireesh Palle",Seed Funding,"850,000",NaN

In [14]:
df[df.dtypes[df.dtypes=='object'].index].describe()

,Date,StartupName,IndustryVertical,SubVertical,CityLocation,InvestorsName,InvestmentType,AmountInUSD,Remarks
count,2372,2372,2201,1436,2193,2364,2371,1525,419
unique,701,2001,743,1364,71,1885,7,329,69
top,02/02/2015,Swiggy,Consumer Internet,Online Pharmacy,Bangalore,Undisclosed Investors,Seed Funding,"1,000,000",Series A
freq,11,7,772,9,627,33,1271,130,177

In [16]:
df.describe

<bound method NDFrame.describe of        SNo        Date       StartupName   IndustryVertical  \
0        0  01/08/2017          TouchKin         Technology
1        1  02/08/2017           Ethinos         Technology
2        2  02/08/2017      Leverage Edu  Consumer Internet
3        3  02/08/2017              Zepo  Consumer Internet
4        4  02/08/2017      Click2Clinic  Consumer Internet
...    ...         ...               ...                ...
2367  2367  29/01/2015        Printvenue                NaN
2368  2368  29/01/2015          Graphene                NaN
2369  2369  30/01/2015    Mad Street Den                NaN
2370  2370  30/01/2015         Simplotel                NaN
2371  2371  31/01/2015  couponmachine.in                NaN

                                        SubVertical CityLocation  \
0                          Predictive Care Platform    Bangalore
1                          Digital Marketing Agency       Mumbai
2     Online platform for Higher Education Services    New Delhi
3                            DIY Ecommerce platform       Mumbai
4                     healthcare service aggregator    Hyderabad
...                                             ...          ...
2367                                            NaN          NaN
2368                                            NaN          NaN
2369                                            NaN          NaN
2370                                            NaN          NaN
2371                                            NaN          NaN

                                          InvestorsName  InvestmentType  \
0                                           Kae Capital  Private Equity
1                            Triton Investment Advisors  Private Equity
2     Kashyap Deorah, Anand Sankeshwar, Deepak Jain,...    Seed Funding
3     Kunal Shah, LetsVenture, Anupam Mittal, Hetal ...    Seed Funding
4                        Narottam Thudi, Shireesh Palle    Seed Funding
...                                                 ...             ...
2367                        Asia Pacific Internet Group  Private Equity
2368                                     KARSEMVEN Fund  Private Equity
2369                     Exfinity Fund, GrowX Ventures.  Private Equity
2370                                         MakeMyTrip  Private Equity
2371                  UK based Group of Angel Investors    Seed Funding

     AmountInUSD                            Remarks
0      1,300,000                                NaN
1            NaN                                NaN
2            NaN                                NaN
3        500,000                                NaN
4        850,000                                NaN
...          ...                                ...
2367   4,500,000                                NaN
2368     825,000                Govt backed VC Fund
2369   1,500,000                                NaN
2370         NaN  Strategic Funding, Minority stake
2371     140,000                                NaN

[2372 rows x 10 columns]>

In [19]:
df.isnull().sum()

SNo                    0
Date                   0
StartupName            0
IndustryVertical     171
SubVertical          936
CityLocation         179
InvestorsName          8
InvestmentType         1
AmountInUSD          847
Remarks             1953
dtype: int64

In [33]:
# Find out what type of startups are getting funded in the last few years?


# so first we seprate the year from the data column and save in the new column year.
## 1. First we change the date type object ot date
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce') # (errors='coerce' will turn invalid entries into NaT instead of crashing.)
df['Date'].dtype

dtype('<M8[ns]')

In [34]:
## Seprate the year from Date
df['Year']=df['Date'].dt.year

,SNo,Date,StartupName,IndustryVertical,SubVertical,CityLocation,InvestorsName,InvestmentType,AmountInUSD,Remarks,Year
0,0,2017-08-01,TouchKin,Technology,Predictive Care Platform,Bangalore,Kae Capital,Private Equity,"1,300,000",NaN,2017.0
1,1,2017-08-02,Ethinos,Technology,Digital Marketing Agency,Mumbai,Triton Investment Advisors,Private Equity,NaN,NaN,2017.0
2,2,2017-08-02,Leverage Edu,Consumer Internet,Online platform for Higher Education Services,New Delhi,"Kashyap Deorah, Anand Sankeshwar, Deepak Jain,...",Seed Funding,NaN,NaN,2017.0
3,3,2017-08-02,Zepo,Consumer Internet,DIY Ecommerce platform,Mumbai,"Kunal Shah, LetsVenture, Anupam Mittal, Hetal ...",Seed Funding,"500,000",NaN,2017.0
4,4,2017-08-02,Click2Clinic,Consumer Internet,healthcare service aggregator,Hyderabad,"Narottam Thudi, Shireesh Palle",Seed Funding,"850,000",NaN,2017.0
...,...,...,...,...,...,...,...,...,...,...,...
2367,2367,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"4,500,000",NaN,2015.0
2368,2368,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"825,000",Govt backed VC Fund,2015.0
2369,2369,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"1,500,000",NaN,2015.0
2370,2370,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake",2015.0
2371,2371,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"140,000",NaN,2015.0